template: "@define" CNAME "-> [" STRING "]" [stmt+]
stmt: struct
    | append
    | set_var

struct: "@struct = [" [_cs_list{STRING}] "]"
append: "@type(" CNAME ")" "-> " CNAME "(" CNAME ")" "= {" [_cs_list{CNAME}] "}"
set_var: CNAME "= {" ANY "}"

ANY: /[^{}]+/
_cs_list{item}: item [("," item)* | (", " item)*] ","?

%import common.CNAME
%import python.STRING

%import common.CPP_COMMENT
%import common.WS

%ignore CPP_COMMENT
%ignore WS